package com.caco3.testtask.songsApi;

import org.json.JSONException;
import org.json.JSONObject;

/**
 * {@link Song} implementation
 */
/* package */ final class SongImpl implements Song {
    private String author;
    private String name;
    private long id;
    private int version;

    @Override
    public String getAuthor() {
        return author;
    }

    @Override
    public String getName() {
        return name;
    }

    @Override
    public long getId() {
        return id;
    }

    @Override
    public int getVersion() {
        return version;
    }

    /* package */ void setVersion(int version){
        this.version = version;
    }

    /* package */ void setId(long id){
        this.id = id;
    }

    /* package */ void setAuthor(String author){
        this.author = author;
    }

    /* package */ void setName(String name){
        this.name = name;
    }



    /**
     * Static factory method. Creates new {@link SongImpl} from json
     * @param json to create from
     * @return {@link SongImpl} created from provided json
     * @throws JSONException if invalid json was provided
     */
    public static Song fromJson(JSONObject json) throws JSONException{
        SongImpl song = new SongImpl();
        song.setName(json.getString("label"));
        song.setAuthor(json.getString("author"));
        song.setId(json.getLong("id"));
        song.setVersion(json.getInt("version"));

        return song;
    }

    // generated by ide
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        SongImpl song = (SongImpl) o;

        if (id != song.id) return false;
        if (version != song.version) return false;
        if (!author.equals(song.author)) return false;
        return name.equals(song.name);

    }

    // generated by ide
    @Override
    public int hashCode() {
        int result = author.hashCode();
        result = 31 * result + name.hashCode();
        result = 31 * result + (int) (id ^ (id >>> 32));
        result = 31 * result + version;
        return result;
    }

    // generated by ide
    @Override
    public String toString() {
        return "SongImpl{" +
                "author='" + author + '\'' +
                ", name='" + name + '\'' +
                ", id=" + id +
                ", version=" + version +
                '}';
    }
}
